[workspace]
members = [
    "server",
    "crates/fnrpc",
    "crates/pool",
    "crates/message",
    "crates/database",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[workspace.dependencies.tracing]
version = "0.1"

[workspace.dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[workspace.dependencies.sqlx]
version = "0.7"
features = [
    "postgres",
    "migrate",
    "runtime-tokio",
    "macros",
]

[workspace.dependencies.waygate-pool]
path = "crates/pool"

[workspace.dependencies.waygate-fnrpc]
path = "crates/fnrpc"

[workspace.dependencies.waygate-message]
path = "crates/message"

[workspace.dependencies.waygate-database]
path = "crates/database"

[workspace.dependencies]
thiserror = "1.0"
