bind = "0.0.0.0:10901"
database_url = "postgresql://postgres:test123@localhost/waygate"
client_public_key = "hQBVt5lmrykxDhcPkCCgNa7YXWYO+OmRPPDTjPugoS4="
server_secret_key = "pkryIBfz7CeyxKbN787xd2j7XUr123F+T0FuRcBwW7s="

[[announcements]]
index = 1
order = 1
title = "[Welcome to online multiplayer world of BINGUSTAN]" 
body = "Bingus is pleased to welcome you to his country.\n"
published_at = 1645681378

[[announcements]]
index = 2
order = 2
title = "[Changelog 0.1.2]" 
body = """
- Reworked config system
- Group passwords now work for messages, bloodstains and ghosts.
"""
published_at = 1645681378


[[announcements]]
index = 2
order = 2
title = "[Changelog 0.1.1]" 
body = """
- Reworked the p2p to improve latency.
- Implemented client mod versioning.
- Added sign puddles.
- Fixed some stability issues with quickmatches.
"""
published_at = 1645681378

[[announcements]]
index = 3
order = 3
title = "[Changelog 0.1.0]" 
body = """
- Added changelog.
- Moved away persistence from diesel to sqlx.
- Made sign/invasion pooling work off of in-memory pools.
- Made passwords work for signs.
"""
published_at = 1645681378
