[[announcements]]
index = 1
order = 1
title = "[Welcome to online multiplayer world of BINGUSTAN]" 
body = "Bingus is pleased to welcome you to his country.\n"
published_at = 1645681378

[[announcements]]
index = 2
order = 2
title = "[Changelog 0.1.1]" 
body = """
- Reworked the p2p to improve latency.
- Implemented client mod versioning.
- Added sign puddles.
- Fixed some stability issues with quickmatches.
"""
published_at = 1645681378

[[announcements]]
index = 3
order = 3
title = "[Changelog 0.1.0]" 
body = """
- Added changelog.
- Moved away persistence from diesel to sqlx.
- Made sign/invasion pooling work off of in-memory pools.
- Made passwords work for signs.
"""
published_at = 1645681378
