[package]
name = "waygate-steam"
version = "0.1.0"
edition = "2021"

[dependencies.steamworks]
git = "https://github.com/vswarte/steamworks-rs"

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true
